---
title: "flat_navbar.Rmd empty"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# navbar

```{r function-navbar}
#' navbar
#'
#' @return a navbar
#' @export
#'
#' @param ... a list of navbar items
#' @param id the id of the navbar item
#' @param title the title of the navbar item
#' @param ui the ui of the navbar item
#' @importFrom htmltools tags tagList
#' @rdname sk_nav
#'
sk_nav <- function(...) {
  uis <- list(...)
  all_ids <- c()
  all_titles <- c()
  all_uis <- list()
  for (ui in uis){
    all_ids <- c(all_ids, ui$id)
    all_titles <- c(all_titles, ui$title)
    all_uis[[length(all_uis) + 1]] <- ui$ui
  }
  tagList(
    # Generating the navbar
    tagList(
      tags$header(
        class = "header",
        tags$nav(
          class = "navbar",
            tags$ul(
              class = "nav-menu",
              lapply(
                1:length(uis),
                {
                  function(idx) {
                    tags$li(
                      class = "nav-item",
                      tags$a(
                        class = "navbar-link",
                        href = "javascript:void(0)",
                        onclick = sprintf("showContent('row-nav-content-item-%s', that = this)", all_ids[idx]),
                        all_titles[idx]
                      )
                    )
                  }
                }
              )
            ),
            tags$div(
              class = "hamburger",
              tags$span(class = "bar"),
              tags$span(class = "bar"),
              tags$span(class = "bar")
            )
        )
      )

    ),
    # Generating the content
    tags$div(
      class = "container",
      lapply(
        1:length(uis), {
          function(idx) {
            tags$div(
              class = "row-nav-content-items",
              id = sprintf("row-nav-content-item-%s", all_ids[idx]),
              all_uis[[idx]],
              style = {
                if (idx != 1) {
                  "display: none;"
                } else {
                  NULL
                }
              }
            )
          }
        }
      )
    )
  )
}
#' @export
#' @rdname sk_nav
#' @importFrom htmltools tags
sk_nav_item <- function(
  id,
  title,
  ui
) {
  list(
    id = id,
    title = title,
    ui = ui
  )
}

```

```{r examples-navbar}
if (FALSE){
  ui <- sk_page(
    sk_row(
      h2("A dead simple, responsive boilerplate."),
    ),
    sk_nav(
      sk_nav_item(
        id = "one",
        title = "ONE",
        ui = sk_row(
          sk_col(
            6,
            "Hello plot1"
          ),
          sk_col(
            6,
            plotOutput("plot1")
          )
        )
      ),
      sk_nav_item(
        id = "two",
        title = "TWO",
        ui = sk_row(
          sk_col(
            6,
            plotOutput("plot2")
          ),
          sk_col(
            6,
            "Hello plot2"
          ),
        )
      ),
      sk_nav_item(
        id = "three",
        title = "THREE",
        ui = sk_row(
          sk_col(
            6,
            plotOutput("plot3")
          ),
          sk_col(
            6,
            "Hello plot3"
          ),
        )
      )
    )
  )
  shinyApp(ui, function(input, output) {
    output$plot1 <- renderPlot({
      plot(mtcars)
    })
    output$plot2 <- renderPlot({
      plot(airquality)
    })
    output$plot3 <- renderPlot({
      plot(pressure)
    })
  })
}
```

```{r tests-navbar}
test_that("navbar works", {
  ui <- sk_page(
    sk_nav(
      sk_nav_item(
        id = "one",
        title = "ONE",
        ui = sk_row(
          sk_col(
            6,
            "Hello plot1"
          ),
          sk_col(
            6,
            "plot1"
          )
        )
      ),
      sk_nav_item(
        id = "two",
        title = "TWO",
        ui = sk_row(
          sk_col(
            6,
            "plot2"
          ),
          sk_col(
            6,
            "Hello plot2"
          ),
        )
      ),
      sk_nav_item(
        id = "three",
        title = "THREE",
        ui = sk_row(
          sk_col(
            6,
            "plot3"
          ),
          sk_col(
            6,
            "Hello plot3"
          ),
        )
      )
    )
  )
  expect_true(
    inherits(ui, "shiny.tag.list")
  )
  expect_true(
    length(ui) == 2
  )
  expect_true(
    any(
      grepl("navbar", ui)
    )
  )
  expect_true(
    any(
      grepl("row-nav-content-item-three", ui)
    )
  )
  expect_true(
    any(
      grepl("row-nav-content-items", ui)
    )
  )
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_navbar.Rmd",
   vignette_name = NA,
   check = FALSE
)
```

