# WARNING - Generated by {fusen} from /dev/flat_page_elements.Rmd: do not edit by hand

test_that("sk_deps works", {
  deps <- sk_deps()
  expect_true(
    inherits(deps, "html_dependency")
  )
  expect_true(
    deps$name == "skeleton-css"
  )
  expect_true(
    deps$version == "2.0.4"
  )
})
