# WARNING - Generated by {fusen} from /dev/flat_page_elements.Rmd: do not edit by hand

test_that("sk_button works", {
  expect_true(
    inherits(
      sk_button("button", "Button"),
      "shiny.tag"
    )
  )
  expect_true(
    grepl(
      "action-button",
      sk_button("button", "Button")[["attribs"]]$class
    )
  )
  expect_true(
    sk_button("button", "Button")[["attribs"]]$id == "button"
  )
  expect_true(
    sk_button("button", "Button")[["attribs"]]$type == "button"
  )
  expect_true(
    inherits(
      sk_button_primary("button", "Button"),
      "shiny.tag"
    )
  )
  expect_true(
    grepl(
      "action-button",
      sk_button_primary("button", "Button")[["attribs"]]$class
    )
  )
  expect_true(
    sk_button_primary("button", "Button")[["attribs"]]$id == "button"
  )
  expect_true(
    sk_button_primary("button", "Button")[["attribs"]]$type == "button"
  )
})
