# WARNING - Generated by {fusen} from /dev/flat_page_elements.Rmd: do not edit by hand

test_that("inputs works", {
  expect_true(
    inherits(
      sk_select_input(
        "reason",
        "Reason for contacting",
        choices = c("Support", "Feedback", "Other")
      ),
      "shiny.tag"
    )
  )
  expect_true(
    inherits(
      sk_text_input(
        "email",
        "Your Email"
      ),
      "shiny.tag"
    )
  )
  expect_true(
    inherits(
      sk_area_input(
        "message",
        "Message",
        placeholder = "hi Dave"
      ),
      "shiny.tag"
    )
  )
})
