# WARNING - Generated by {fusen} from /dev/flat_golem_hook.Rmd: do not edit by hand

test_that("skboilerplate works", {
  skip_if_not_installed("golem")
  old <- setwd(tempdir())
  on.exit(setwd(old))
  unlink("skboilerplate", recursive = TRUE)
  golem::create_golem(
    "skboilerplate",
    project_hook = ghook_sk_boilerplate
  )
  expect_true(
    any(
      grepl(
        "sk_page",
        readLines("R/app_ui.R")
      )
    )
  )
  expect_true(
    any(
      grepl(
        "skeleton",
        readLines("R/app_ui.R")
      )
    )
  )
  expect_true(
    golem::is_golem(".")
  )
})
test_that("skdashboard works", {
  skip_if_not_installed("golem")
  old <- setwd(tempdir())
  on.exit(setwd(old))
  unlink("skdashboard", recursive = TRUE)
  golem::create_golem(
    "skdashboard",
    project_hook = ghook_sk_dashboard
  )
  expect_true(
    file.exists("R/mod_tab1.R")
  )
  expect_true(
    file.exists("R/mod_tab2.R")
  )
  expect_true(
    any(
      grepl(
        "mod_tab1_ui",
        readLines("R/app_ui.R")
      )
    )
  )
  expect_true(
    any(
      grepl(
        "skeleton",
        readLines("R/app_ui.R")
      )
    )
  )
  expect_true(
    golem::is_golem(".")
  )
})
