# WARNING - Generated by {fusen} from /dev/flat_navbar.Rmd: do not edit by hand

test_that("navbar works", {
  ui <- sk_page(
    sk_nav(
      sk_nav_item(
        id = "one",
        title = "ONE",
        ui = sk_row(
          sk_col(
            6,
            "Hello plot1"
          ),
          sk_col(
            6,
            "plot1"
          )
        )
      ),
      sk_nav_item(
        id = "two",
        title = "TWO",
        ui = sk_row(
          sk_col(
            6,
            "plot2"
          ),
          sk_col(
            6,
            "Hello plot2"
          ),
        )
      ),
      sk_nav_item(
        id = "three",
        title = "THREE",
        ui = sk_row(
          sk_col(
            6,
            "plot3"
          ),
          sk_col(
            6,
            "Hello plot3"
          ),
        )
      )
    )
  )
  expect_true(
    inherits(ui, "shiny.tag.list")
  )
  expect_true(
    length(ui) == 2
  )
  expect_true(
    any(
      grepl("navbar", ui)
    )
  )
  expect_true(
    any(
      grepl("row-nav-content-item-three", ui)
    )
  )
  expect_true(
    any(
      grepl("row-nav-content-items", ui)
    )
  )
})
