# WARNING - Generated by {fusen} from /dev/flat_page_elements.Rmd: do not edit by hand

test_that("utils works", {
  expect_equal(
    to_letter(1),
    "one column"
  )
  expect_equal(
    to_letter(2),
    "two columns"
  )
  expect_equal(
    to_letter(3),
    "three columns"
  )
  expect_equal(
    to_letter(4),
    "four columns"
  )
  expect_equal(
    to_letter(5),
    "five columns"
  )
  expect_equal(
    to_letter(6),
    "six columns"
  )
  expect_equal(
    to_letter(7),
    "seven columns"
  )
  expect_equal(
    to_letter(8),
    "eight columns"
  )
  expect_equal(
    to_letter(9),
    "nine columns"
  )
  expect_equal(
    to_letter(10),
    "ten columns"
  )
  expect_equal(
    to_letter(11),
    "eleven columns"
  )
  expect_equal(
    to_letter(12),
    "twelve columns"
  )

})
