# WARNING - Generated by {fusen} from /dev/flat_page_elements.Rmd: do not edit by hand

test_that("sk_page works", {
  pg <- sk_page(
    "Hello world"
  )
  expect_true(
    inherits(pg, "shiny.tag.list")
  )
  expect_error(
    sk_col(0, "Hello world")
  )
  expect_error(
    sk_col(13, "Hello world")
  )
})

test_that("sk_row works", {
  expect_true(
    inherits(
      sk_row("Hello world"),
      "shiny.tag"
    )
  )
  expect_true(
    sk_row("Hello world")[["attribs"]]$class == "row"
  )
})

test_that("sk_col works", {
  expect_true(
    sk_col(1, "Hello world")[["attribs"]]$class == "one column"
  )
  expect_true(
    sk_col(2, "Hello world")[["attribs"]]$class == "two columns"
  )
  expect_true(
    sk_col(3, "Hello world")[["attribs"]]$class == "three columns"
  )
  expect_true(
    sk_col(4, "Hello world")[["attribs"]]$class == "four columns"
  )
  expect_true(
    sk_col(5, "Hello world")[["attribs"]]$class == "five columns"
  )
  expect_true(
    sk_col(6, "Hello world")[["attribs"]]$class == "six columns"
  )
  expect_true(
    sk_col(7, "Hello world")[["attribs"]]$class == "seven columns"
  )
  expect_true(
    sk_col(8, "Hello world")[["attribs"]]$class == "eight columns"
  )
  expect_true(
    sk_col(9, "Hello world")[["attribs"]]$class == "nine columns"
  )
  expect_true(
    sk_col(10, "Hello world")[["attribs"]]$class == "ten columns"
  )
  expect_true(
    sk_col(11, "Hello world")[["attribs"]]$class == "eleven columns"
  )
  expect_true(
    sk_col(12, "Hello world")[["attribs"]]$class == "twelve columns"
  )
  expect_true(
    sk_col_one_third("Hello world")[["attribs"]]$class == "one-third column"
  )
  expect_true(
    sk_col_one_half("Hello world")[["attribs"]]$class == "one-half column"
  )
  expect_true(
    sk_col_two_third("Hello world")[["attribs"]]$class == "two-thirds column"
  )
  expect_true(
    sk_col_one_third("Hello world", id = "my_id")[["attribs"]]$id == "my_id"
  )
  expect_true(
    sk_col_one_half("Hello world", id = "my_id")[["attribs"]]$id == "my_id"
  )
  expect_true(
    sk_col_two_third("Hello world", id = "my_id")[["attribs"]]$id == "my_id"
  )
})
