# WARNING - Generated by {fusen} from /dev/flat_page_elements.Rmd: do not edit by hand

#' Buttons
#'
#' Standard & primary buttons
#'
#' @return an actionButton
#'
#' @export
#' @inheritParams shiny::actionButton
#' @rdname sk_buttons
#'
#' @examples
#' if (FALSE) {
#'   ui <- sk_page(
#'     h1("Hello world"),
#'     sk_row(
#'       sk_col(6, "Hello"),
#'       sk_col(6, "World"),
#'       sk_button("button", "Button"),
#'       sk_button_primary("button_primary", "Button primary")
#'     )
#'   )
#'
#'   server <- function(input, output) {
#'     # Server code goes here
#'     observeEvent(input$button, {
#'       print("Hello standard button")
#'     })
#'     observeEvent(input$button_primary, {
#'       print("Hello button_primary")
#'     })
#'   }
#'   shinyApp(ui, server)
#' }
sk_button <- function(
  inputId,
  label,
  ...
    ) {
  shiny::actionButton(
    inputId = inputId,
    label = label,
    ...
  )
}
#' @export
#' @rdname sk_buttons
#'
sk_button_primary <- function(
  inputId,
  label,
  ...
    ) {
  shiny::actionButton(
    inputId = inputId,
    label = label,
    class = "button-primary",
  )
}
