# WARNING - Generated by {fusen} from /dev/flat_page_elements.Rmd: do not edit by hand

#' Inputs
#'
#' Skeleton inputs
#'
#' @return an input tag (selectInput, textInput, textAreaInput)
#' @param ... arguments passed to the `selectInput` function
#'
#' @export
#' @rdname sk_inputs
#'
#' @importFrom shiny selectInput
#' @examples
#' if (FALSE) {
#'   ui <- sk_page(
#'     h1("Hello world"),
#'     sk_row(
#'       sk_col(
#'         6,
#'         sk_text_input(
#'           "email",
#'           "Your Email"
#'         )
#'       ),
#'       sk_col(
#'         6,
#'         sk_select_input(
#'           "reason",
#'           "Reason for contacting"
#'         )
#'       ),
#'       sk_col(
#'         12,
#'         sk_area_input(
#'           "message",
#'           "Message",
#'           placeholder = "hi Dave"
#'         )
#'       ),
#'       sk_button("send", "Send")
#'     )
#'   )
#' 
#'   server <- function(input, output) {
#'     # Server code goes here
#'     observeEvent(input$button, {
#'       print("Hello standard button")
#'     })
#'     observeEvent(input$button_primary, {
#'       print("Hello button_primary")
#'     })
#'   }
#'   shinyApp(ui, server)
#' }
sk_select_input <- function(
  ...
){
  selectInput(
    ...
  )
}
#' @export
#' @rdname sk_inputs
#'
#' @importFrom shiny textInput
sk_text_input <- function(
  ...
){
  textInput(
    ...
  )
}
#' @export
#' @rdname sk_inputs
#'
#' @importFrom shiny textAreaInput
sk_area_input <- function(
  ...
){
  textAreaInput(
    ...
  )
}
