# WARNING - Generated by {fusen} from /dev/flat_navbar.Rmd: do not edit by hand

#' navbar
#'
#' @return a navbar
#' @export
#'
#' @param ... a list of navbar items
#' @param id the id of the navbar item
#' @param title the title of the navbar item
#' @param ui the ui of the navbar item
#' @importFrom htmltools tags tagList
#' @rdname sk_nav
#'
#' @examples
#' if (FALSE){
#'   ui <- sk_page(
#'     sk_row(
#'       h2("A dead simple, responsive boilerplate."),
#'     ),
#'     sk_nav(
#'       sk_nav_item(
#'         id = "one",
#'         title = "ONE",
#'         ui = sk_row(
#'           sk_col(
#'             6,
#'             "Hello plot1"
#'           ),
#'           sk_col(
#'             6,
#'             plotOutput("plot1")
#'           )
#'         )
#'       ),
#'       sk_nav_item(
#'         id = "two",
#'         title = "TWO",
#'         ui = sk_row(
#'           sk_col(
#'             6,
#'             plotOutput("plot2")
#'           ),
#'           sk_col(
#'             6,
#'             "Hello plot2"
#'           ),
#'         )
#'       ),
#'       sk_nav_item(
#'         id = "three",
#'         title = "THREE",
#'         ui = sk_row(
#'           sk_col(
#'             6,
#'             plotOutput("plot3")
#'           ),
#'           sk_col(
#'             6,
#'             "Hello plot3"
#'           ),
#'         )
#'       )
#'     )
#'   )
#'   shinyApp(ui, function(input, output) {
#'     output$plot1 <- renderPlot({
#'       plot(mtcars)
#'     })
#'     output$plot2 <- renderPlot({
#'       plot(airquality)
#'     })
#'     output$plot3 <- renderPlot({
#'       plot(pressure)
#'     })
#'   })
#' }
sk_nav <- function(...) {
  uis <- list(...)
  all_ids <- c()
  all_titles <- c()
  all_uis <- list()
  for (ui in uis){
    all_ids <- c(all_ids, ui$id)
    all_titles <- c(all_titles, ui$title)
    all_uis[[length(all_uis) + 1]] <- ui$ui
  }
  tagList(
    # Generating the navbar
    tagList(
      tags$nav(
        class = "navbar",
        tags$div(
          class = "container",
          tags$ul(
            class = "navbar-list",
            lapply(
              1:length(uis), {
                function(idx) {
                  tags$li(
                    class = "navbar-item",
                    tags$a(
                      class = "navbar-link",
                      href = "javascript:void(0)",
                      onclick = sprintf("showContent('row-nav-content-item-%s', that = this)", all_ids[idx]),
                      all_titles[idx]
                    )
                  )
                }
              }
            )
          )
        )
      )
    ),
    # Generating the content
    tags$div(
      class = "container",
      lapply(
        1:length(uis), {
          function(idx) {
            tags$div(
              class = "row-nav-content-items",
              id = sprintf("row-nav-content-item-%s", all_ids[idx]),
              all_uis[[idx]],
              style = {
                if (idx != 1) {
                  "display: none;"
                } else {
                  NULL
                }
              }
            )
          }
        }
      )
    )
  )
}
#' @export
#' @rdname sk_nav
#' @importFrom htmltools tags
sk_nav_item <- function(
  id,
  title,
  ui
) {
  list(
    id = id,
    title = title,
    ui = ui
  )
}

