# WARNING - Generated by {fusen} from /dev/flat_page_elements.Rmd: do not edit by hand

#' Skeleton Page
#'
#' @param id The id of the element
#' @param width The width of the element
#' @param ... The content of the element
#' @param title The title of the page
#' @return A skeleton html element
#'
#' @export
#' @rdname sk_page
#'
#' @importFrom htmltools tags
#' @examples
#' if (FALSE) {
#'   ui <- sk_page(
#'     tags$style(
#'       ".columns, .column {
#'         background: #EEE;
#'         text-align: center;
#'         border-radius: 4px;
#'         margin-bottom: 1.5rem;
#'       }"
#'     ),
#'     sk_row(
#'       h2("A dead simple, responsive boilerplate."),
#'     ),
#'     sk_row(
#'       tags$p(
#'         "The grid is a 12-column fluid grid with a max width of 960px,",
#'         "that shrinks with the browser/device at smaller sizes.",
#'         "The max width can be changed with one line of CSS and",
#'         "all columns will resize accordingly.",
#'         "The syntax is simple and it makes coding",
#'         "responsive much easier. Go ahead, resize the browser."
#'       )
#'     ),
#'     sk_row(
#'       sk_col(1, "ONE"),
#'       sk_col(11, "ELEVEN")
#'     ),
#'     sk_row(
#'       sk_col(2, "TWO"),
#'       sk_col(10, "TEN"),
#'     ),
#'     sk_row(
#'       sk_col(3, "THREE"),
#'       sk_col(9, "NINE")
#'     ),
#'     sk_row(
#'       sk_col(4, "FOUR"),
#'       sk_col(8, "EIGHT")
#'     ),
#'     sk_row(
#'       sk_col(5, "FIVE"),
#'       sk_col(7, "SEVEN")
#'     ),
#'     sk_row(
#'       sk_col(6, "SIX"),
#'       sk_col(6, "SIX")
#'     )
#'   )
#'   shinyApp(ui, function(input, output) {
#'     # Server code goes here
#'   })
#' }
#' 
sk_page <- function(...) {
  tagList(
    sk_deps(),
    tags$body(
      tags$div(
        class = "container",
        ...
      )
    )
  )
}

#' @export
#' @rdname sk_page
#'
#' @importFrom htmltools tags
sk_row <- function(..., id = NULL) {
  tags$div(
    id = id,
    class = "row",
    ...
  )
}

#' @export
#' @rdname sk_page
#'
#' @importFrom htmltools tags
sk_col <- function(width, ..., id = NULL) {
    if (width < 1 || width > 12) {
      stop("width must be between 1 and 12 included")
    }
  tags$div(
    id = id,
    class = to_letter(width),
    ...
  )
}

#' @export
#' @rdname sk_page
#'
#' @importFrom htmltools tags
sk_col_one_third <- function(..., id = NULL) {
  tags$div(
    id = id,
    class = "one-third column",
    ...
  )
}

#' @export
#' @rdname sk_page
#'
#' @importFrom htmltools tags
sk_col_one_half <- function( ..., id = NULL) {
  tags$div(
    id = id,
    class = "one-half column",
    ...
  )
}

#' @export
#' @rdname sk_page
#'
#' @importFrom htmltools tags
sk_col_two_third <- function(..., id = NULL) {
  tags$div(
    id = id,
    class = "two-thirds column",
    ...
  )
}

#' @export
#' @rdname sk_page
#'
#' @importFrom htmltools tags h2
sk_header <- function(title, ...) {
  tags$section(
    class = "header",
    h2(
      class = "title",
      title
    ),
    ...
  )
}
